In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.randn(5, 3)
print(x)

tensor([[-0.7683,  0.0931,  0.8262],
        [-1.2706,  0.1124,  0.0401],
        [-0.7056, -1.8234, -1.2193],
        [-2.5125,  0.1501, -1.5134],
        [-0.4281,  0.0411, -0.4004]])


In [6]:
print(x.unsqueeze(-1).size())
print(x.unsqueeze(-1))

torch.Size([5, 3, 1])
tensor([[[-0.7683],
         [ 0.0931],
         [ 0.8262]],

        [[-1.2706],
         [ 0.1124],
         [ 0.0401]],

        [[-0.7056],
         [-1.8234],
         [-1.2193]],

        [[-2.5125],
         [ 0.1501],
         [-1.5134]],

        [[-0.4281],
         [ 0.0411],
         [-0.4004]]])


In [7]:
print(x.unsqueeze(0).size())
print(x.unsqueeze(0))

torch.Size([1, 5, 3])
tensor([[[-0.7683,  0.0931,  0.8262],
         [-1.2706,  0.1124,  0.0401],
         [-0.7056, -1.8234, -1.2193],
         [-2.5125,  0.1501, -1.5134],
         [-0.4281,  0.0411, -0.4004]]])


In [32]:
x = torch.arange(5)
print(x)

tensor([0, 1, 2, 3, 4])


In [33]:
input_ids = torch.randn(6, 5)

In [34]:
y = x.unsqueeze(0).expand_as(input_ids)
print(y.size())
print(y)

torch.Size([6, 5])
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


In [35]:
input_ids + y

tensor([[-1.3660, -0.5786,  1.7638,  2.6149,  4.0512],
        [ 0.3708,  1.7772,  0.8333,  1.8551,  4.4225],
        [ 0.1582,  2.3185,  3.1922,  4.1859,  3.7819],
        [-0.5010,  2.4481,  1.5786,  2.9478,  6.5719],
        [-0.4295,  0.9404,  3.2049,  2.4340,  4.9176],
        [ 0.8830,  0.2227,  1.6426,  1.9117,  3.0786]])

In [36]:
token_type_ids = torch.zeros_like(input_ids)
print(token_type_ids)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [37]:
word_embeddings = nn.Embedding(5, 6)
position_embeddings = nn.Embedding(6, 6)
token_type_embdeeings = nn.Embedding(5, 6)

In [47]:
print(word_embeddings.weight.size())
word_embeddings.weight

torch.Size([5, 6])


Parameter containing:
tensor([[ 0.9075, -0.5447, -0.1960,  1.4023,  1.0694, -0.7083],
        [-0.9668,  0.3845,  1.3396, -0.4193, -0.1964,  0.4551],
        [ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918],
        [ 1.1343,  0.3401,  0.6819, -0.6285,  0.1113, -0.7056],
        [ 0.7004,  0.2623,  0.3865, -0.0138, -0.6555,  1.2747]],
       requires_grad=True)

In [49]:
print(word_embeddings(torch.arange(5)).size())
word_embeddings(torch.arange(5))

torch.Size([5, 6])


tensor([[[ 0.9075, -0.5447, -0.1960,  1.4023,  1.0694, -0.7083]],

        [[-0.9668,  0.3845,  1.3396, -0.4193, -0.1964,  0.4551]],

        [[ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918]],

        [[ 1.1343,  0.3401,  0.6819, -0.6285,  0.1113, -0.7056]],

        [[ 0.7004,  0.2623,  0.3865, -0.0138, -0.6555,  1.2747]]],
       grad_fn=<EmbeddingBackward>)

In [50]:
print(word_embeddings(torch.arange(5).view(5, -1)).size())
word_embeddings(torch.arange(5).view(5, -1))

torch.Size([5, 1, 6])


tensor([[[ 0.9075, -0.5447, -0.1960,  1.4023,  1.0694, -0.7083]],

        [[-0.9668,  0.3845,  1.3396, -0.4193, -0.1964,  0.4551]],

        [[ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918]],

        [[ 1.1343,  0.3401,  0.6819, -0.6285,  0.1113, -0.7056]],

        [[ 0.7004,  0.2623,  0.3865, -0.0138, -0.6555,  1.2747]]],
       grad_fn=<EmbeddingBackward>)

In [52]:
word_embeddings(torch.tensor(2))

tensor([ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918],
       grad_fn=<EmbeddingBackward>)

In [53]:
torch.tensor(2)

tensor(2)