In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math

### 행렬 요소 연산

In [2]:
x = torch.randn(5, 3)
print(x)
print(x+1)

tensor([[-0.8374, -1.2301, -0.7227],
        [-0.8427, -0.1762, -0.4047],
        [-0.0641,  0.3220,  1.1210],
        [ 0.2619, -0.2958,  2.6746],
        [ 0.7297, -0.1729, -0.3651]])
tensor([[ 0.1626, -0.2301,  0.2773],
        [ 0.1573,  0.8238,  0.5953],
        [ 0.9359,  1.3220,  2.1210],
        [ 1.2619,  0.7042,  3.6746],
        [ 1.7297,  0.8271,  0.6349]])


### unsqueeze, squeeze

In [3]:
print(x.unsqueeze(-1).size())
print(x.unsqueeze(-1))

torch.Size([5, 3, 1])
tensor([[[ 1.0147],
         [ 0.5510],
         [ 1.2563]],

        [[-0.6739],
         [-1.0578],
         [-0.7639]],

        [[ 0.3787],
         [-0.4891],
         [ 1.1139]],

        [[ 1.1028],
         [-0.9469],
         [-1.3231]],

        [[-0.0905],
         [ 0.0940],
         [-0.3365]]])


In [4]:
print(x.unsqueeze(0).size())
print(x.unsqueeze(0))

torch.Size([1, 5, 3])
tensor([[[ 1.0147,  0.5510,  1.2563],
         [-0.6739, -1.0578, -0.7639],
         [ 0.3787, -0.4891,  1.1139],
         [ 1.1028, -0.9469, -1.3231],
         [-0.0905,  0.0940, -0.3365]]])


In [5]:
x = torch.arange(5)
print(x)

tensor([0, 1, 2, 3, 4])


In [6]:
input_ids = torch.randn(6, 5)

### expand_as

In [7]:
y = x.unsqueeze(0).expand_as(input_ids)
print(y.size())
print(y)

torch.Size([6, 5])
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


In [8]:
input_ids + y

tensor([[ 0.3160,  1.0719,  3.2948,  3.5629,  5.0383],
        [-0.5004,  2.2755,  1.5341,  3.1248,  5.0559],
        [-1.7600,  1.7466,  2.6826,  2.1746,  4.7072],
        [ 0.4642,  1.8645,  0.9007,  3.8681,  4.3930],
        [-0.2154,  0.5208,  2.7829,  3.2703,  4.5508],
        [-0.2529,  1.6966,  2.1995,  4.2893,  4.5484]])

In [9]:
token_type_ids = torch.zeros_like(input_ids)
print(token_type_ids)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### nn.Embedding

In [12]:
word_embeddings = nn.Embedding(5, 6, padding_idx=0)
print('word', word_embeddings.weight.size())
position_embeddings = nn.Embedding(6, 6)
token_type_embdeeings = nn.Embedding(5, 6)

word torch.Size([5, 6])


In [13]:
print(word_embeddings.weight.size())
word_embeddings.weight

torch.Size([5, 6])


Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147],
        [ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483],
        [-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938],
        [-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]],
       requires_grad=True)

In [14]:
print(word_embeddings(torch.arange(5)).size())
word_embeddings(torch.arange(5))

torch.Size([5, 6])


tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147],
        [ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483],
        [-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938],
        [-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]],
       grad_fn=<EmbeddingBackward>)

In [16]:
print(torch.arange(5).view(5, -1))
print(word_embeddings(torch.arange(5).view(5, -1)).size())
word_embeddings(torch.arange(5).view(5, -1))

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([5, 1, 6])


tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147]],

        [[ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483]],

        [[-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938]],

        [[-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]]],
       grad_fn=<EmbeddingBackward>)

In [52]:
word_embeddings(torch.tensor(2))

tensor([ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918],
       grad_fn=<EmbeddingBackward>)

In [53]:
torch.tensor(2)

tensor(2)

### nn.Linear 연산 low level 구현

In [75]:
input1 = torch.ones(3, 2, dtype=torch.float)
print(input1.size())
print(input1)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [76]:
layer1 = nn.Linear(2, 3, bias=False)
print(layer1.weight.size())
print(layer1.weight.T)

torch.Size([3, 2])
tensor([[-0.2503, -0.3038, -0.3790],
        [-0.4319, -0.7004, -0.4276]], grad_fn=<PermuteBackward>)


In [77]:
output1 = layer1(input1)
print(output1.size())
print(output1)

torch.Size([3, 3])
tensor([[-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066]], grad_fn=<MmBackward>)


In [78]:
tmp_layer1 = layer1.weight
print(input1.matmul(tmp_layer1.T)) # input * layer 연산처럼 계산이 된다
print(tmp_layer1.matmul(input1.T))

tensor([[-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066]], grad_fn=<MmBackward>)
tensor([[-0.6822, -0.6822, -0.6822],
        [-1.0042, -1.0042, -1.0042],
        [-0.8066, -0.8066, -0.8066]], grad_fn=<MmBackward>)


In [80]:
layer1.weight

Parameter containing:
tensor([[-0.2503, -0.4319],
        [-0.3038, -0.7004],
        [-0.3790, -0.4276]], requires_grad=True)

### multihead attention 연산 및 contiguous 확인해보기

In [115]:
t1 = torch.randn([32, 128, 768])
print(t1.size())
new_shape = t1.size()[:-1] + (12, 64)
print(new_shape)
q = t1.view(new_shape)
print(q.size())
k = t1.view(*new_shape)
print(k.size())
v = t1.view(*new_shape)
print(v.size())
q = q.permute(0, 2, 1, 3)
print(q.size())
k = k.permute(0, 2, 1, 3)
print(k.size())
v = v.permute(0, 2, 1, 3)
print(v.size())

torch.Size([32, 128, 768])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 12, 128, 64])
torch.Size([32, 12, 128, 64])
torch.Size([32, 12, 128, 64])


In [116]:
k.transpose(-1, -2).size()

torch.Size([32, 12, 64, 128])

In [117]:
a = torch.matmul(q, k.transpose(-1, -2))
print(a.size())

torch.Size([32, 12, 128, 128])


In [118]:
result = torch.matmul(a, v)
print(result.size())

torch.Size([32, 12, 128, 64])


In [120]:
c = result.permute(0, 2, 1, 3).contiguous()
print(c.size())
new_c_shape = c.size()[:-2] + (768,)
c = c.view(new_c_shape)
print(c.size())

torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 768])


In [122]:
# permute 연산을 할 때는 반드시 contiguous() 이용하자
c = result.permute(0, 2, 1, 3)
print(c.size())
new_c_shape = c.size()[:-2] + (768,)
print(new_c_shape)
c = c.view(new_c_shape)
print(c.size())

torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 768])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### attention head size 만큼 왜 먼저 나누지 않고 matmul 하고 split 했는가?

In [16]:
# 테크닉적 관점에서 유리 > 연산량을 줄이기 위해 matmul 하고 split 
# 결국 잘라진 head_size 만큼을 열에 이어 붙여(concat) 웨이트 계산을 하므로 서로 다른 head_size 가 연관되지 않을 수 있다
batch_size = 1
seq_length = 1
hidden_size = 128
num_heads = 8
head_size = int(hidden_size / num_heads)
all_head_size = num_heads * head_size

hidden_states = torch.randn(batch_size, seq_length, hidden_size)
print(hidden_states.size())

w_query = nn.Linear(hidden_size, all_head_size)
w_key = nn.Linear(hidden_size, all_head_size)
w_vlaue = nn.Linear(hidden_size, all_head_size)
print(w_query.weight.size())

torch.Size([1, 1, 128])
torch.Size([128, 128])


In [17]:
query = w_query(hidden_states)
print(query.size())

torch.Size([1, 1, 128])


### 각종 mask 구현

In [3]:
inputs = torch.tensor([[3091, 3604,  206, 3958, 3760, 3590,    0,    0],
                       [ 212, 3605,   53, 3832, 3596, 3682, 3760, 3590]])

In [9]:
def get_attn_pad_mask(seq_q, seq_k):
    # print(seq_q)
    batch_size, len_q = seq_q.size()
    batch_size, len_k = seq_k.size()
    # eq(zero) is PAD token
    pad_attn_mask = seq_k.data.eq(0).unsqueeze(1)  # batch_size x 1 x len_k(=len_q), one is masking
    return pad_attn_mask.expand(batch_size, len_q, len_k)  # batch_size x len_q x len_k

def transpose_for_attention_scores(x):
    new_x_shape = x.size()[:-1] + (num_heads, head_size)
    x = x.view(new_x_shape)
    return x.permute(0, 2, 1, 3)

In [20]:
attention_mask = get_attn_pad_mask(inputs, inputs)
print(attention_mask.size())
attention_mask = attention_mask.unsqueeze(1).repeat(1, num_heads, 1, 1)
print(attention_mask.size())

torch.Size([2, 8, 8])
torch.Size([2, 8, 8, 8])


### repeat 함수

In [46]:
# expand 와 역할이 비슷
attn_mask2 = inputs.eq(0).unsqueeze(1).repeat(1, inputs.size()[1], 1)
print(attn_mask2.size())
print(attn_mask2[0])

torch.Size([2, 8, 8])
tensor([[False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True]])


In [21]:
print(attention_mask[0][0])

tensor([[False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True]])


In [22]:
word_embeddings = nn.Embedding(5000, 128)

### masked_fill_ 함수

In [28]:
enc_inputs = word_embeddings(inputs)
print(enc_inputs.size())
q = transpose_for_attention_scores(enc_inputs)
k = transpose_for_attention_scores(enc_inputs)
v = transpose_for_attention_scores(enc_inputs)
print(q.size())
scores = torch.matmul(q, k.transpose(-1, -2)) / math.sqrt(head_size)
print(scores.size())
print(scores[0][0])
scores.masked_fill_(attention_mask, -1e9) # inplace=True 라고 이해
print(scores[0][0])

torch.Size([2, 8, 128])
torch.Size([2, 8, 8, 16])
torch.Size([2, 8, 8, 8])
tensor([[ 4.6761,  0.0964, -0.8392,  1.0350,  0.6139, -0.7481,  1.7292,  1.7292],
        [ 0.0964,  5.7820, -0.2166,  0.5408,  0.4307, -0.2465,  1.4741,  1.4741],
        [-0.8392, -0.2166,  5.6125, -0.5546, -0.5507, -0.0594,  0.7508,  0.7508],
        [ 1.0350,  0.5408, -0.5546,  4.2115,  0.0281,  0.6837, -0.0087, -0.0087],
        [ 0.6139,  0.4307, -0.5507,  0.0281,  6.2815,  0.3990, -0.3775, -0.3775],
        [-0.7481, -0.2465, -0.0594,  0.6837,  0.3990,  2.5180, -0.5743, -0.5743],
        [ 1.7292,  1.4741,  0.7508, -0.0087, -0.3775, -0.5743,  3.4868,  3.4868],
        [ 1.7292,  1.4741,  0.7508, -0.0087, -0.3775, -0.5743,  3.4868,  3.4868]],
       grad_fn=<SelectBackward>)
tensor([[ 4.6761e+00,  9.6396e-02, -8.3923e-01,  1.0350e+00,  6.1386e-01,
         -7.4811e-01, -1.0000e+09, -1.0000e+09],
        [ 9.6396e-02,  5.7820e+00, -2.1659e-01,  5.4077e-01,  4.3070e-01,
         -2.4650e-01, -1.0000e+09, -1.

In [42]:
position_ids = torch.arange(inputs.size()[1], dtype=torch.long, device=inputs.device)
print(position_ids)
position_ids = position_ids.unsqueeze(0).expand_as(inputs) + 1
position_mask = inputs.eq(0)
print(position_mask.size())
print(position_mask)
position_ids.masked_fill_(position_mask, 0)
print(position_ids.size())
print(position_ids)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
torch.Size([2, 8])
tensor([[False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False, False, False]])
torch.Size([2, 8])
tensor([[1, 2, 3, 4, 5, 6, 0, 0],
        [1, 2, 3, 4, 5, 6, 7, 8]])


In [5]:
position = torch.arange(inputs.size()[1], dtype=torch.long, device=inputs.device)
print(position)
position = position.unsqueeze(0).expand_as(input_ids) + 1
print(position)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [11]:
batch_size, seq_length = inputs.size()
mask1 = inputs.eq(0).unsqueeze(1).repeat(1, seq_length, 1)
print(mask1.size())
print(mask1)
mask2 = inputs.eq(0).unsqueeze(1).expand(-1, seq_length, seq_length)
print(mask2.size())
print(mask2)

torch.Size([2, 8, 8])
tensor([[[False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True]],

        [[False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, 

In [10]:
get_attn_pad_mask(inputs, inputs)

tensor([[[False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False,  True,  True]],

        [[False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, F

### nn.functional.relu vs nn.relu

In [33]:
relu1 = nn.functional.relu
relu2 = nn.ReLU()
relu2(inputs)

tensor([[3091, 3604,  206, 3958, 3760, 3590,    0,    0],
        [ 212, 3605,   53, 3832, 3596, 3682, 3760, 3590]])

### triu 함수

In [13]:
seq_length = inputs.size()[1]
look_ahead_attention_mask = torch.ones_like(inputs).unsqueeze(1).expand(-1, seq_length, seq_length)
look_ahead_attention_mask = look_ahead_attention_mask.triu(diagonal=1)
print(look_ahead_attention_mask.size())
print(look_ahead_attention_mask)

torch.Size([2, 8, 8])
tensor([[[0, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0]]])


In [14]:
look_ahead_attention_mask + mask1

tensor([[[0, 1, 1, 1, 1, 1, 2, 2],
         [0, 0, 1, 1, 1, 1, 2, 2],
         [0, 0, 0, 1, 1, 1, 2, 2],
         [0, 0, 0, 0, 1, 1, 2, 2],
         [0, 0, 0, 0, 0, 1, 2, 2],
         [0, 0, 0, 0, 0, 0, 2, 2],
         [0, 0, 0, 0, 0, 0, 1, 2],
         [0, 0, 0, 0, 0, 0, 1, 1]],

        [[0, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0]]])

In [23]:
torch.FloatTensor(look_ahead_attention_mask.data)

TypeError: expected Float (got Long)

In [24]:
look_ahead_attention_mask.type(torch.FloatTensor)

tensor([[[0., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

### tensor device

In [29]:
inputs.device

device(type='cpu')

In [30]:
inputs2 = inputs.to('cuda:0')
print(inputs2.device)

cuda:0


In [32]:
embedding = nn.Embedding(5000, 128).to('cuda:0')
output = embedding(inputs2)
print(output.device)

cuda:0


### check max and loss function

In [26]:
x = torch.randn(2, 4, 6)
print(x.size())
print(x)

torch.Size([2, 4, 6])
tensor([[[-0.6938,  0.1457, -0.9835,  1.3099, -0.9390,  0.8756],
         [ 0.2593,  0.8409, -0.4726,  0.1268,  0.7458, -0.0990],
         [-0.9609, -0.1394,  0.7400,  0.9022,  0.7582,  2.0940],
         [ 0.2643, -1.0782, -0.8420,  0.7802, -0.3221,  0.2543]],

        [[ 0.6597, -1.5837,  1.6594, -1.6289,  1.5789,  0.3306],
         [-0.0280,  0.0883,  0.6994,  1.8595, -1.4196, -0.1731],
         [ 1.5204, -1.1727,  1.0850, -0.7173,  1.0063, -0.5371],
         [-0.0202, -0.9994, -0.2342, -0.3674,  0.2583, -0.3927]]])


In [29]:
x1 = x.data.max(1, keepdim=True)
print(x1[0].size())
print(x1)

torch.Size([2, 1, 6])
torch.return_types.max(
values=tensor([[[0.2643, 0.8409, 0.7400, 1.3099, 0.7582, 2.0940]],

        [[1.5204, 0.0883, 1.6594, 1.8595, 1.5789, 0.3306]]]),
indices=tensor([[[3, 1, 2, 0, 2, 2]],

        [[2, 1, 0, 1, 0, 0]]]))


In [15]:
y = torch.max(x, dim=-1)[1]
print(y.size())
print(y)

torch.Size([2, 4])
tensor([[3, 3, 5, 2],
        [2, 3, 2, 4]])


### nn.CrossEntoropyLoss() 모듈

In [16]:
loss = nn.CrossEntropyLoss()

In [63]:
# 이미 Softmax 연산이 들어가 있다!!! 기억해야할 중요한 특징
x = torch.randn(3, 5, requires_grad=True)
print(x.type())
print(x)
target = torch.empty(3, dtype=torch.long).random_(5)
print(target.size(), target.type())
print(target)
# x [학습 데이터 개수, 예측할 클래스 개수]  
# target [학습 데이터 개수]  각 요소의 값의 범위는 0<= 요소 값 < 예측할 클래스 개수
output = loss(x, target) 
output.backward()

torch.FloatTensor
tensor([[ 1.4663,  1.8633, -1.3971,  0.9727, -0.8936],
        [-0.0059,  0.7120, -0.6675,  0.5047,  0.7541],
        [-0.8697, -1.3655,  0.5656, -0.2357, -0.2611]], requires_grad=True)
torch.Size([3]) torch.LongTensor
tensor([0, 4, 4])


In [22]:
output

tensor(2.3157, grad_fn=<NllLossBackward>)

In [25]:
print(target)

tensor([0, 4, 1])


### contiguous 역할 확인

In [58]:
x = torch.randn(1, 12)
print('x', x)
x1 = x.view(6, 1, 2)  # view 는 contiguous 관계없이 잘만 연산된다...
print('x1', x1.size(), x1)
x2 = x1.view(-1, 6)
print('x2', x2.size(), x2)

x tensor([[ 0.7520,  0.9209,  1.7477,  0.2112, -0.7485, -1.6528,  1.4142, -0.2038,
         -0.4447, -1.2773, -0.7338,  0.2586]])
x1 torch.Size([6, 1, 2]) tensor([[[ 0.7520,  0.9209]],

        [[ 1.7477,  0.2112]],

        [[-0.7485, -1.6528]],

        [[ 1.4142, -0.2038]],

        [[-0.4447, -1.2773]],

        [[-0.7338,  0.2586]]])
x2 torch.Size([2, 6]) tensor([[ 0.7520,  0.9209,  1.7477,  0.2112, -0.7485, -1.6528],
        [ 1.4142, -0.2038, -0.4447, -1.2773, -0.7338,  0.2586]])


In [61]:
x = torch.randn(3, 4)
print('x', x)
x1 = x.T.contiguous()
print('x1', x1.size(), x1)
x2 = x1.view(-1, 12)
print('x2', x2.size(), x2)

x tensor([[-1.3997,  0.8185,  1.1836,  2.0959],
        [ 0.5977, -0.2876, -0.8078,  1.1232],
        [-0.1020, -1.0201, -0.9303,  0.8226]])
x1 torch.Size([4, 3]) tensor([[-1.3997,  0.5977, -0.1020],
        [ 0.8185, -0.2876, -1.0201],
        [ 1.1836, -0.8078, -0.9303],
        [ 2.0959,  1.1232,  0.8226]])
x2 torch.Size([1, 12]) tensor([[-1.3997,  0.5977, -0.1020,  0.8185, -0.2876, -1.0201,  1.1836, -0.8078,
         -0.9303,  2.0959,  1.1232,  0.8226]])


In [64]:
x = torch.randn(3, 4)
print('x', x)
x1 = x.T
print('x1', x1.size(), x1)
x2 = x1.view(-1, 12)
print('x2', x2.size(), x2)

x tensor([[-0.3530, -0.7585,  0.1002,  0.1007],
        [-0.3664,  0.7023, -1.3625,  0.1680],
        [-0.5170, -0.6264, -0.8493,  0.7772]])
x1 torch.Size([4, 3]) tensor([[-0.3530, -0.3664, -0.5170],
        [-0.7585,  0.7023, -0.6264],
        [ 0.1002, -1.3625, -0.8493],
        [ 0.1007,  0.1680,  0.7772]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### softmax 함수를 2번 거치면 안되는 이유!!

In [34]:
x = torch.randn(1, 4)
print(x)
y = nn.Softmax(dim=-1)(x)
print(y)
z = nn.Softmax(dim=-1)(y)
print(z)

tensor([[1.1489, 0.8749, 1.7694, 0.0402]])
tensor([[0.2532, 0.1925, 0.4708, 0.0835]])
tensor([[0.2482, 0.2336, 0.3086, 0.2095]])


### 특정 인덱스에 있는 배열들끼리 loss 함수 연산

In [2]:
criterion = nn.CrossEntropyLoss()

In [22]:
logits = torch.cat((torch.randint(low=1, high=100, size=(3, 5)), torch.zeros(3, 5)), dim=1).long()
print(logits)

tensor([[15, 94, 79, 12, 63,  0,  0,  0,  0,  0],
        [45, 78, 27, 58, 97,  0,  0,  0,  0,  0],
        [46, 51, 32, 46, 44,  0,  0,  0,  0,  0]])


In [118]:
logits = torch.randn(32, 64, 64)

tensor([[[-0.5601, -0.5249,  1.2889,  ...,  0.3411, -1.3962, -1.2489],
         [-0.8170,  1.2406, -0.9008,  ...,  0.2952,  0.4377,  0.4691],
         [ 0.7496,  0.1983, -0.4119,  ...,  0.2676, -2.1124, -0.2258],
         ...,
         [-0.1310, -0.9929,  0.0581,  ..., -0.5869, -2.3567, -0.0658],
         [-0.8745,  0.6750, -0.1264,  ...,  0.1858, -1.0787, -0.3986],
         [-0.6307,  0.9805,  0.6117,  ...,  0.7772,  0.5498, -0.5344]],

        [[ 0.7131,  3.5618,  1.4272,  ...,  0.4929, -0.4648,  0.6625],
         [ 0.5249, -1.0449, -1.0311,  ..., -1.3840,  1.6824, -0.9098],
         [ 0.2124,  0.1566, -0.7641,  ...,  0.2226, -0.8025, -2.0636],
         ...,
         [-1.6686, -0.1605, -0.4563,  ..., -0.8832,  0.8574,  0.2229],
         [ 0.4103,  0.6757,  0.5089,  ..., -0.9261, -0.8572,  0.3098],
         [-1.4222, -0.4565,  1.1931,  ...,  0.6827,  0.6277,  0.0635]],

        [[-0.9394, -0.4340, -0.1077,  ..., -1.3675,  0.1026,  0.3075],
         [ 0.5232,  1.1724,  0.1237,  ...,  0

In [119]:
target = torch.cat((torch.randint(63, (32, 40)), torch.zeros(32, 24).long()), dim=1)
#print(target)

In [120]:
logits = logits.view(-1, 64)
print('logits', logits.size())
target = target.view(-1)
print('target', target.size())
loss = criterion(logits, target)
print(loss)

logits torch.Size([2048, 64])
target torch.Size([2048])
tensor(4.6720)


In [109]:
print(target)
mask = target.eq(0)
mask2 = target.gt(0)
print(mask)
print(mask2)
print(torch.masked_select(target, mask))
print(torch.masked_select(target, mask2))

tensor([55, 58, 40, 53,  9,  0,  0,  0, 30,  2, 57, 60, 23,  0,  0,  0])
tensor([False, False, False, False, False,  True,  True,  True, False, False,
        False, False, False,  True,  True,  True])
tensor([ True,  True,  True,  True,  True, False, False, False,  True,  True,
         True,  True,  True, False, False, False])
tensor([0, 0, 0, 0, 0, 0])
tensor([55, 58, 40, 53,  9, 30,  2, 57, 60, 23])


In [110]:
indices = target.nonzero()
print(indices.size())
indices = indices.squeeze(1)
print(indices.size())

torch.Size([10, 1])
torch.Size([10])


In [111]:
nonzero_select = target.nonzero().squeeze(1)
print(nonzero_select)
logits.index_select(0, nonzero_select)[9]

tensor([ 0,  1,  2,  3,  4,  8,  9, 10, 11, 12])


tensor([-4.4530e-01, -2.0959e+00,  3.4911e-01,  1.1928e+00,  1.8318e+00,
         1.0213e+00,  8.9384e-01, -1.5533e-03,  4.3959e-01, -5.1688e-01,
        -3.6100e-01, -5.7435e-01,  1.3810e+00, -9.9748e-01,  9.3622e-01,
         5.8957e-01, -9.8576e-01,  2.1106e+00, -7.5180e-01, -6.9673e-01,
         9.5892e-01,  3.6880e-02,  3.0920e-01,  1.2280e-01, -6.3096e-01,
        -4.0947e-03, -1.1701e+00, -8.1369e-01,  1.3854e+00, -1.0662e+00,
         4.1882e-01, -8.3795e-01,  1.9905e-02,  5.0381e-02, -5.8051e-03,
        -2.6111e-01, -2.1081e-01,  2.6515e-01, -1.7769e+00,  1.4315e+00,
         9.8287e-01, -1.4567e+00, -1.8326e+00,  1.2404e+00,  8.7852e-01,
        -4.3018e-01,  1.0892e+00,  2.8672e-01,  1.0150e+00,  8.9820e-01,
         2.9182e-01, -4.4006e-01,  6.1617e-01,  2.3243e-01, -2.4432e-02,
        -1.1542e+00,  6.4300e-02,  7.9511e-01, -1.1673e+00,  8.3426e-01,
        -1.7161e-01, -1.5478e+00, -5.3831e-01, -1.0625e+00])

In [112]:
logits[12]

tensor([-4.4530e-01, -2.0959e+00,  3.4911e-01,  1.1928e+00,  1.8318e+00,
         1.0213e+00,  8.9384e-01, -1.5533e-03,  4.3959e-01, -5.1688e-01,
        -3.6100e-01, -5.7435e-01,  1.3810e+00, -9.9748e-01,  9.3622e-01,
         5.8957e-01, -9.8576e-01,  2.1106e+00, -7.5180e-01, -6.9673e-01,
         9.5892e-01,  3.6880e-02,  3.0920e-01,  1.2280e-01, -6.3096e-01,
        -4.0947e-03, -1.1701e+00, -8.1369e-01,  1.3854e+00, -1.0662e+00,
         4.1882e-01, -8.3795e-01,  1.9905e-02,  5.0381e-02, -5.8051e-03,
        -2.6111e-01, -2.1081e-01,  2.6515e-01, -1.7769e+00,  1.4315e+00,
         9.8287e-01, -1.4567e+00, -1.8326e+00,  1.2404e+00,  8.7852e-01,
        -4.3018e-01,  1.0892e+00,  2.8672e-01,  1.0150e+00,  8.9820e-01,
         2.9182e-01, -4.4006e-01,  6.1617e-01,  2.3243e-01, -2.4432e-02,
        -1.1542e+00,  6.4300e-02,  7.9511e-01, -1.1673e+00,  8.3426e-01,
        -1.7161e-01, -1.5478e+00, -5.3831e-01, -1.0625e+00])

In [114]:
print(target)
target.index_select(0, nonzero_select)

tensor([55, 58, 40, 53,  9,  0,  0,  0, 30,  2, 57, 60, 23,  0,  0,  0])


tensor([55, 58, 40, 53,  9, 30,  2, 57, 60, 23])

In [101]:
idx = target.nonzero().max()
print(idx)
print(logits[:idx].size())

tensor(12)
torch.Size([12, 64])


In [103]:
logits[:idx+1][-1]

tensor([-4.4530e-01, -2.0959e+00,  3.4911e-01,  1.1928e+00,  1.8318e+00,
         1.0213e+00,  8.9384e-01, -1.5533e-03,  4.3959e-01, -5.1688e-01,
        -3.6100e-01, -5.7435e-01,  1.3810e+00, -9.9748e-01,  9.3622e-01,
         5.8957e-01, -9.8576e-01,  2.1106e+00, -7.5180e-01, -6.9673e-01,
         9.5892e-01,  3.6880e-02,  3.0920e-01,  1.2280e-01, -6.3096e-01,
        -4.0947e-03, -1.1701e+00, -8.1369e-01,  1.3854e+00, -1.0662e+00,
         4.1882e-01, -8.3795e-01,  1.9905e-02,  5.0381e-02, -5.8051e-03,
        -2.6111e-01, -2.1081e-01,  2.6515e-01, -1.7769e+00,  1.4315e+00,
         9.8287e-01, -1.4567e+00, -1.8326e+00,  1.2404e+00,  8.7852e-01,
        -4.3018e-01,  1.0892e+00,  2.8672e-01,  1.0150e+00,  8.9820e-01,
         2.9182e-01, -4.4006e-01,  6.1617e-01,  2.3243e-01, -2.4432e-02,
        -1.1542e+00,  6.4300e-02,  7.9511e-01, -1.1673e+00,  8.3426e-01,
        -1.7161e-01, -1.5478e+00, -5.3831e-01, -1.0625e+00])