In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.randn(5, 3)
print(x)

tensor([[ 1.0147,  0.5510,  1.2563],
        [-0.6739, -1.0578, -0.7639],
        [ 0.3787, -0.4891,  1.1139],
        [ 1.1028, -0.9469, -1.3231],
        [-0.0905,  0.0940, -0.3365]])


In [3]:
print(x.unsqueeze(-1).size())
print(x.unsqueeze(-1))

torch.Size([5, 3, 1])
tensor([[[ 1.0147],
         [ 0.5510],
         [ 1.2563]],

        [[-0.6739],
         [-1.0578],
         [-0.7639]],

        [[ 0.3787],
         [-0.4891],
         [ 1.1139]],

        [[ 1.1028],
         [-0.9469],
         [-1.3231]],

        [[-0.0905],
         [ 0.0940],
         [-0.3365]]])


In [4]:
print(x.unsqueeze(0).size())
print(x.unsqueeze(0))

torch.Size([1, 5, 3])
tensor([[[ 1.0147,  0.5510,  1.2563],
         [-0.6739, -1.0578, -0.7639],
         [ 0.3787, -0.4891,  1.1139],
         [ 1.1028, -0.9469, -1.3231],
         [-0.0905,  0.0940, -0.3365]]])


In [5]:
x = torch.arange(5)
print(x)

tensor([0, 1, 2, 3, 4])


In [6]:
input_ids = torch.randn(6, 5)

In [7]:
y = x.unsqueeze(0).expand_as(input_ids)
print(y.size())
print(y)

torch.Size([6, 5])
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


In [8]:
input_ids + y

tensor([[ 0.3160,  1.0719,  3.2948,  3.5629,  5.0383],
        [-0.5004,  2.2755,  1.5341,  3.1248,  5.0559],
        [-1.7600,  1.7466,  2.6826,  2.1746,  4.7072],
        [ 0.4642,  1.8645,  0.9007,  3.8681,  4.3930],
        [-0.2154,  0.5208,  2.7829,  3.2703,  4.5508],
        [-0.2529,  1.6966,  2.1995,  4.2893,  4.5484]])

In [9]:
token_type_ids = torch.zeros_like(input_ids)
print(token_type_ids)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
word_embeddings = nn.Embedding(5, 6, padding_idx=0)
print('word', word_embeddings.weight.size())
position_embeddings = nn.Embedding(6, 6)
token_type_embdeeings = nn.Embedding(5, 6)

word torch.Size([5, 6])


In [13]:
print(word_embeddings.weight.size())
word_embeddings.weight

torch.Size([5, 6])


Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147],
        [ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483],
        [-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938],
        [-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]],
       requires_grad=True)

In [14]:
print(word_embeddings(torch.arange(5)).size())
word_embeddings(torch.arange(5))

torch.Size([5, 6])


tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147],
        [ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483],
        [-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938],
        [-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]],
       grad_fn=<EmbeddingBackward>)

In [16]:
print(torch.arange(5).view(5, -1))
print(word_embeddings(torch.arange(5).view(5, -1)).size())
word_embeddings(torch.arange(5).view(5, -1))

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([5, 1, 6])


tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.4579,  1.0892, -0.3312, -0.2074, -0.4237,  0.9147]],

        [[ 0.3414, -1.5100,  0.0070,  1.5652,  0.0486,  1.8483]],

        [[-0.1010, -1.2528, -0.2252, -0.0108,  0.2299,  0.1938]],

        [[-0.6949, -0.8128, -1.5756,  0.8243, -0.0091,  0.6609]]],
       grad_fn=<EmbeddingBackward>)

In [52]:
word_embeddings(torch.tensor(2))

tensor([ 0.0524,  0.4486,  0.7723, -0.5151,  0.5046,  0.1918],
       grad_fn=<EmbeddingBackward>)

In [53]:
torch.tensor(2)

tensor(2)

In [75]:
input1 = torch.ones(3, 2, dtype=torch.float)
print(input1.size())
print(input1)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [76]:
layer1 = nn.Linear(2, 3, bias=False)
print(layer1.weight.size())
print(layer1.weight.T)

torch.Size([3, 2])
tensor([[-0.2503, -0.3038, -0.3790],
        [-0.4319, -0.7004, -0.4276]], grad_fn=<PermuteBackward>)


In [77]:
output1 = layer1(input1)
print(output1.size())
print(output1)

torch.Size([3, 3])
tensor([[-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066]], grad_fn=<MmBackward>)


In [78]:
tmp_layer1 = layer1.weight
print(input1.matmul(tmp_layer1.T))
print(tmp_layer1.matmul(input1.T))

tensor([[-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066],
        [-0.6822, -1.0042, -0.8066]], grad_fn=<MmBackward>)
tensor([[-0.6822, -0.6822, -0.6822],
        [-1.0042, -1.0042, -1.0042],
        [-0.8066, -0.8066, -0.8066]], grad_fn=<MmBackward>)


In [80]:
layer1.weight

Parameter containing:
tensor([[-0.2503, -0.4319],
        [-0.3038, -0.7004],
        [-0.3790, -0.4276]], requires_grad=True)

In [115]:
t1 = torch.randn([32, 128, 768])
print(t1.size())
new_shape = t1.size()[:-1] + (12, 64)
print(new_shape)
q = t1.view(new_shape)
print(q.size())
k = t1.view(*new_shape)
print(k.size())
v = t1.view(*new_shape)
print(v.size())
q = q.permute(0, 2, 1, 3)
print(q.size())
k = k.permute(0, 2, 1, 3)
print(k.size())
v = v.permute(0, 2, 1, 3)
print(v.size())

torch.Size([32, 128, 768])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 12, 64])
torch.Size([32, 12, 128, 64])
torch.Size([32, 12, 128, 64])
torch.Size([32, 12, 128, 64])


In [116]:
k.transpose(-1, -2).size()

torch.Size([32, 12, 64, 128])

In [117]:
a = torch.matmul(q, k.transpose(-1, -2))
print(a.size())

torch.Size([32, 12, 128, 128])


In [118]:
result = torch.matmul(a, v)
print(result.size())

torch.Size([32, 12, 128, 64])


In [120]:
c = result.permute(0, 2, 1, 3).contiguous()
print(c.size())
new_c_shape = c.size()[:-2] + (768,)
c = c.view(new_c_shape)
print(c.size())

torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 768])


In [122]:
c = result.permute(0, 2, 1, 3)
print(c.size())
new_c_shape = c.size()[:-2] + (768,)
print(new_c_shape)
c = c.view(new_c_shape)
print(c.size())

torch.Size([32, 128, 12, 64])
torch.Size([32, 128, 768])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.