# PyTorch 튜토리얼

## tensors

In [1]:
from __future__ import print_function
import torch

#### 아무렇게 생긴 5x3 행렬을 생성 (거의 0에 근접한 값들)

In [18]:
x = torch.Tensor(5, 3)
print(x)

tensor([[9.0919e-39, 1.0102e-38, 8.9082e-39],
        [4.9592e-39, 9.2755e-39, 1.0837e-38],
        [8.4490e-39, 1.1112e-38, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39]])


#### 0~1 사이의 표준정규분포를 따르는 5x3 행렬을 생성

In [25]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8646, 0.6302, 0.4800],
        [0.4777, 0.1250, 0.7168],
        [0.9009, 0.3995, 0.4215],
        [0.8011, 0.5351, 0.9651],
        [0.3361, 0.8172, 0.5214]])


#### 평균: 0, 분산: 1인 가우시안 분포를 따르는 5x3 행렬을 생성

In [32]:
x = torch.randn(5, 3)
print(x)

tensor([[-1.3301,  0.6931, -0.5831],
        [-0.9291,  0.8846, -0.3285],
        [ 0.9854, -0.7752, -0.3939],
        [-1.6797, -0.1288,  1.1985],
        [ 1.8402, -0.0271,  0.4624]])


#### size() : 행렬의 크기 구하기

In [35]:
x.size()

torch.Size([5, 3])

In [36]:
print(x.size())

torch.Size([5, 3])


#### 인자를 통해 행렬의 특정 차원 수를 반환할 수 있음

In [37]:
x.size(1)

3

In [39]:
x.size(0)

5

In [42]:
x.size(-1)

3

In [43]:
#### size() : 반환 인자는 int

In [40]:
type(x.size(0))

int

## 연산(operations)

#### 덧셈

In [67]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
x + y

tensor([[0.2229, 1.1458, 0.5305],
        [0.8631, 1.1674, 0.5129],
        [1.0027, 0.8195, 1.0511],
        [0.9385, 1.1129, 1.1782],
        [0.1847, 0.7676, 1.3886]])

In [68]:
print(x + y)

tensor([[0.2229, 1.1458, 0.5305],
        [0.8631, 1.1674, 0.5129],
        [1.0027, 0.8195, 1.0511],
        [0.9385, 1.1129, 1.1782],
        [0.1847, 0.7676, 1.3886]])


In [69]:
torch.add(x, y)

tensor([[0.2229, 1.1458, 0.5305],
        [0.8631, 1.1674, 0.5129],
        [1.0027, 0.8195, 1.0511],
        [0.9385, 1.1129, 1.1782],
        [0.1847, 0.7676, 1.3886]])

#### 결과를 tensor 인자를 통해 제공 가능

In [70]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result

tensor([[0.2229, 1.1458, 0.5305],
        [0.8631, 1.1674, 0.5129],
        [1.0027, 0.8195, 1.0511],
        [0.9385, 1.1129, 1.1782],
        [0.1847, 0.7676, 1.3886]])

#### in-place 방식: 접미사 _ 를 붙인다

In [71]:
y

tensor([[0.1737, 0.3077, 0.4390],
        [0.7793, 0.4107, 0.1562],
        [0.4381, 0.0797, 0.1302],
        [0.1171, 0.8048, 0.7788],
        [0.0760, 0.5779, 0.9070]])

In [72]:
y += x
y

tensor([[0.2229, 1.1458, 0.5305],
        [0.8631, 1.1674, 0.5129],
        [1.0027, 0.8195, 1.0511],
        [0.9385, 1.1129, 1.1782],
        [0.1847, 0.7676, 1.3886]])

In [73]:
y.add_(x)
y

tensor([[0.2720, 1.9839, 0.6220],
        [0.9469, 1.9242, 0.8697],
        [1.5672, 1.5593, 1.9720],
        [1.7599, 1.4209, 1.5777],
        [0.2935, 0.9573, 1.8702]])

In [74]:
x

tensor([[0.0492, 0.8381, 0.0915],
        [0.0838, 0.7567, 0.3567],
        [0.5646, 0.7398, 0.9209],
        [0.8214, 0.3080, 0.3994],
        [0.1087, 0.1897, 0.4816]])

In [75]:
x.t_()

tensor([[0.0492, 0.0838, 0.5646, 0.8214, 0.1087],
        [0.8381, 0.7567, 0.7398, 0.3080, 0.1897],
        [0.0915, 0.3567, 0.9209, 0.3994, 0.4816]])

In [76]:
x

tensor([[0.0492, 0.0838, 0.5646, 0.8214, 0.1087],
        [0.8381, 0.7567, 0.7398, 0.3080, 0.1897],
        [0.0915, 0.3567, 0.9209, 0.3994, 0.4816]])

#### cf) 한 차원 수가 다르면 broadcasting 이 적용됨

In [77]:
x = torch.rand(5, 3)
x

tensor([[0.0622, 0.6601, 0.1942],
        [0.3262, 0.7404, 0.6542],
        [0.3084, 0.0925, 0.0538],
        [0.7346, 0.5777, 0.9791],
        [0.8568, 0.5275, 0.0739]])

In [78]:
y = torch.rand(5, 1)
y

tensor([[0.7167],
        [0.5605],
        [0.3666],
        [0.3561],
        [0.3313]])

In [79]:
x + y

tensor([[0.7789, 1.3768, 0.9110],
        [0.8868, 1.3010, 1.2147],
        [0.6750, 0.4591, 0.4204],
        [1.0907, 0.9338, 1.3352],
        [1.1881, 0.8588, 0.4052]])

#### numpy 에서 쓰이는 인덱싱 사용 가능

In [81]:
x[:, 1]

tensor([0.6601, 0.7404, 0.0925, 0.5777, 0.5275])

#### 크기 변경 : torch.view를 이용

In [83]:
x = torch.rand(4, 4)
x

tensor([[0.2726, 0.3717, 0.0180, 0.9897],
        [0.7911, 0.4069, 0.2232, 0.0699],
        [0.1153, 0.7568, 0.2410, 0.9924],
        [0.2192, 0.4715, 0.1044, 0.9112]])

In [84]:
y = x.view(16)
y

tensor([0.2726, 0.3717, 0.0180, 0.9897, 0.7911, 0.4069, 0.2232, 0.0699, 0.1153,
        0.7568, 0.2410, 0.9924, 0.2192, 0.4715, 0.1044, 0.9112])

In [85]:
z = x.view(-1, 8)
z

tensor([[0.2726, 0.3717, 0.0180, 0.9897, 0.7911, 0.4069, 0.2232, 0.0699],
        [0.1153, 0.7568, 0.2410, 0.9924, 0.2192, 0.4715, 0.1044, 0.9112]])

In [87]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### torch tensor를 numpy 배열로 변환

In [89]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [91]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

#### 참조가 사용된 것인가?

In [92]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [93]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

#### numpy 배열을 torch tensor 로 변환

In [95]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [96]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [97]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [98]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

# Autograd : 자동 미분 (autograd 패키지)

## 변수 (Variable)

In [99]:
import torch
from torch.autograd import Variable

#### 변수 생성

In [161]:
x = Variable(torch.ones(2, 2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

#### data attribute

In [162]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [146]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

#### 연산을 수행했으므로 y는 grad_fn이란 attribute를 가짐

In [147]:
y.grad_fn

In [148]:
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [149]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

## 변화도 (Gradient)

In [150]:
out.backward()

In [151]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

#### 변화도 측정의 다른 예제

In [177]:
x = torch.randn(1, 3)
x = Variable(x, requires_grad=True)
x

tensor([[ 2.1810,  0.0365, -0.1339]], requires_grad=True)

In [178]:
y = x * 2
y

tensor([[ 4.3620,  0.0729, -0.2679]], grad_fn=<MulBackward0>)

#### norm() : 각 요소를 더하고 root를 취한 값

In [179]:
y.data.norm()

tensor(4.3708)

In [180]:
while y.data.norm() < 1000:
    y = y * 2
y

tensor([[1116.6775,   18.6725,  -68.5769]], grad_fn=<MulBackward0>)

#### 다양한 요소의 변화도를 구할 수 있음

In [181]:
gradients = torch.FloatTensor([[0.1, 1.0, 0.001]])
y.backward(gradients)

In [183]:
x.grad

tensor([[ 51.2000, 512.0000,   0.5120]])